on:
  workflow_dispatch:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: '.'
      image-tag:
        required: true
        type: string
    outputs:
      app_url:
        description: "The ECS application URL"
        value: ${{ jobs.deploy.outputs.app_url }}
      app_ip:
        description: "The ECS application public ip"
        value: ${{ jobs.deploy.outputs.app_ip }}
name: cd

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    outputs:
      app_url: ${{ steps.set_app_url.outputs.app_url }}
      app_ip:  ${{ steps.set_app_ip.outputs.app_ip }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Echo
        run: echo "CD... image-tag ${{ inputs.image-tag }}"

      # TODO
      # Configure AWS credentials
      # Deploy ECS Cluster using templates/cluster.yaml
      # Update ECS Task Definition with image tag
      # Deploy new ECS Task
      # Output the app URL